In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])

In [4]:
print(x)

[1 2 3 4]


In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [6]:
print(x.shape)

(4,)


In [8]:
y=np.array([[2,3],[4,6]])

In [9]:
print(y)

[[2 3]
 [4 6]]


In [10]:
print(type(y))

<class 'numpy.ndarray'>


In [11]:
print(y.shape)

(2, 2)


In [13]:
z=np.array([[1+0.j,2+5.j]])

In [14]:
print(type(z))
print(z)
print(z.shape)

<class 'numpy.ndarray'>
[[1.+0.j 2.+5.j]]
(1, 2)


In [15]:
a=np.zeros((2,3))

In [16]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
print(a.shape)

(2, 3)


In [19]:
b=np.ones((4,4), dtype=int) 

In [20]:
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [21]:
d=np.eye(3)

In [22]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
e=np.arange(11)

In [24]:
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [25]:
e=np.arange(11,25)

In [26]:
print(e)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [27]:
e=np.arange(5,21,2)

In [28]:
print(e)

[ 5  7  9 11 13 15 17 19]


In [33]:
f = np.linspace(1,20,7)

In [34]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [35]:
g=np.random.random((3,4))

In [36]:
print(g)

[[0.46304494 0.8875154  0.16769681 0.82140048]
 [0.12836061 0.04542339 0.72036082 0.82138522]
 [0.85526989 0.55947844 0.68473382 0.59635684]]


In [40]:
print(g.reshape(2,2,3))

[[[0.46304494 0.8875154  0.16769681]
  [0.82140048 0.12836061 0.04542339]]

 [[0.72036082 0.82138522 0.85526989]
  [0.55947844 0.68473382 0.59635684]]]


In [41]:
x=np.arange(12)
print(x)
print(x[5])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
5


In [42]:
print(x[-2])

10


In [44]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
x.resize(4,3)

In [46]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [47]:
print (x[-1,-1])

11


In [48]:
print(x[2][2])

8


In [50]:
print(x[3][2])

11


In [51]:
y=np.arange(1,10)
print(y)
print(y[:4])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4]


In [53]:
print(y[5:])

[6 7 8 9]


In [54]:
print(y[1:4])

[2 3 4]


In [55]:
print(y[-5:])

[5 6 7 8 9]


In [56]:
print(y[-3:-1])

[7 8]


In [57]:
print(y[::2])

[1 3 5 7 9]


In [61]:
y = np.arange(1,26)

In [62]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [63]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [64]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [65]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [67]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [66]:
print(y[:,-1])

[ 5 10 15 20 25]


In [68]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [69]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [71]:

a=np.arange(1,6)
b=np.arange(6,11)
print(a)
print(b)
print(a+b)
print(a-b)
print(b-a)
print(a**2)


[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [72]:
print(a>3)

[False False False  True  True]


In [73]:
a = np.arange(0,4).reshape((2,2))

In [74]:
b = np.eye(2)

In [75]:
print(a*b)

[[0. 0.]
 [0. 3.]]


In [76]:
print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [77]:
x = np.arange(1,10).reshape(3,3)

In [78]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
print(x.sum())

45


In [80]:
print(x.sum(axis=0))

[12 15 18]


In [81]:
print(x.sum(axis=1))

[ 6 15 24]


In [82]:
x = np.arange(1,19).reshape(3,3,2)

In [83]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [84]:
x = np.arange(1,10).reshape(3,3)

In [85]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [86]:
print(x.max(axis=0))

[7 8 9]


In [87]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
