In [17]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix


In [18]:
irisData = load_iris()

In [19]:
X = irisData.data
y = irisData.target

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [21]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)


In [22]:
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [23]:
y_pred = nb.predict(X_test)
y_pred

array([2, 1, 1, 1, 2, 0, 0, 1, 1, 2, 2, 1, 0, 1, 1, 1, 2, 2, 0, 0, 2, 2,
       0, 0, 1, 0, 2, 2, 2, 1])

In [24]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [25]:
print(accuracy_score(y_test,y_pred)*100)

100.0
